const nodemailer = require('nodemailer')
const dotenv = require('dotenv')
dotenv.config();

const sendMail = (options) => {

let mailConfig = {}
let sendGrid = {
    service: process.env.EMAIL_SERVICE,
    host: process.env.HOST,
    auth: {
        user: process.env.EMAIL_USERNAME,
        pass: process.env.EMAIL_PASSWORD
    }
}


let smtpConfig = {
    // host: process.env.SMTP_HOST,
    // port: 2525,
    // secure: true, // use SSL
    // auth: {
    //     user: process.env.SMTP_USER,
    //     pass: process.env.SMTP_PASS
    // }
   
    // host: 'mailhog',
    // port: 1025

  
        host: "54.236.89.180",
        // host: "smtp.mailtrap.io",
        secure: true,
        port: 2525,
        auth: {
          user: "cd08a8ff3c2cb5", //generated by Mailtrap
          pass: "1fe12ec7e49500" //generated by Mailtrap
        },
        // tls: {
        //     servername: 'smtp.mailtrap.io'
        // }
      
};

if(process.env.NODE_ENV === 'development') {
    mailConfig = smtpConfig
    // mailConfig = sendGrid
} else {
    mailConfig = sendGrid
}



    // let transporter = nodemailer.createTransport(smtpConfig)
    let transporter = nodemailer.createTransport(
        // mailConfig
        {
            // host: "54.236.89.180",
            host: "smtp.mailtrap.io",
            secure: true,
            port: 2525,
            auth: {
              user: "cd08a8ff3c2cb5",
              pass: "1fe12ec7e49500"
            }
        }
        );

    const mailOptions = {
        from: process.env.EMAIL_FROM,
        to: options.to,
        subject: options.subject,
        html: options.text
    }

   

    transporter.sendMail(mailOptions, function(err,info) {
        if(err){
            console.log(err)
        } else {
            console.log(info)
        }
    })

    transporter.verify(function(error, success) {
        if (error) {
             console.log(error);
        } else {
             console.log('Server is ready to take our messages');
        }
     });


}


module.exports = sendMail;